
language: python
python:
  - "3.6"

sudo: required

os:
  - linux
  #- osx
  #- windows


# command to install dependencies
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install ffmpeg ; fi
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg ; fi
  #- if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install ffmpeg; fi

install:
  - pip install -r requirements.txt
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
# command to run tests


before_script:
  - herbstluftwm &
  - sleep 3

script:
  - pytest --cov src/ test/ --verbose --cov-report term-missing

after_success:
  - codecov