language: python
python:
  - "3.6"

os:
  - linux
  #- osx
  #- windows

matrix:
  include:
    - os: windows
      language: shell
      python: "3.7"
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

      before_install:
        - choco install python3
        - pip install virtualenv
        #- export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
        - choco install ffmpeg
        - export PATH=$PATH:";C:\ProgramData\chocolatey\lib\ffmpeg\tools"
        - echo $PATH
      install:
        - pip install -r requirements-test.txt
      script:
        - xvfb-run make test
        - pytest --cov src/ test/ --verbose --cov-report term-missing
        #C:\ProgramData\chocolatey\lib\ffmpeg\tools
    - os: linux

# command to install dependencies
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install ffmpeg ; fi
  #- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg ; fi
  #- if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install ffmpeg; fi

install:
  - pip install -r requirements.txt
# command to run tests
script:
  - xvfb-run make test
  - pytest --cov src/ test/ --verbose --cov-report term-missing