language: python
python:
  - "3.6"

os:
  - linux
  - osx
  #- windows

# command to install dependencies
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install ffmpeg ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg ; fi
  #- if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install ffmpeg; fi

install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov src/ test/ --verbose --cov-report term-missing