language: python
python:
  - "3.7"
  - "3.7-dev"

# command to install dependencies
install:
  - sudo apt install ffmpeg
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest --cov src/ test/ --verbose